### ISSUE TITLE
Unable to get assignment after network address

### ISSUE THREAD

**Issue by XTH1996** [staskobzar/vue-audio-visual#105]
Why can't addresses requested via Ajax be rendered,
![image](https://user-images.githubusercontent.com/44921948/170235617-ee3e75b9-4d84-4f4a-be08-a8d40169e3bd.png)
![image](https://user-images.githubusercontent.com/44921948/170235915-35dd5627-7d99-4170-b513-8c9d3a4bf2ad.png)
This address is correct

**Comment by staskobzar** [comment]
make sure that you can play this address in your browser in another tab.
Does it work when you put address in the component element prop "audio-src"?

If you dynamically assign address then it should be assigned before component is rendered.
for example:
```
<av-waveform v-if="urlPath" />
...
...
if (ok) {
   this.urlPath = 'http://......'
}
```
Another problem can be different sources, when page base URL address is different from audio file base URL.
then you can try to set cross-origin setting.

**Comment by XTH1996** [comment]
Thank you very much! I have solved the problem!
