### ISSUE TITLE
Build error using Vuetify: Unexpected token: punc ())

### ISSUE THREAD

**Issue by karuban88** [staskobzar/vue-audio-visual#11]
I got this error when trying to build the app in production mode.

ERROR in static/js/vendor.e8bb63ea9110771343a2.js from UglifyJs
Unexpected token: punc ()) [./~/vue-audio-visual/src/components/AvCircle.js:102,0][static/js/vendor.e8bb63ea9110771343a2.js:60172,14]

**Comment by staskobzar** [comment]
When I do "npm run build" in the project folder, I see no errors.
Can you give more details? How to reproduce the problem.
Thanks.
