### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/vue.js?v=d2d7e806' does not provide an export named 'default' 

### ISSUE THREAD

**Issue by wty92911** [staskobzar/vue-audio-visual#122]
when I use "import {AVPlugin} from 'vue-audio-visual'" in my project the browser warns.
How should I deal with it ?

**Comment by staskobzar** [comment]
Hello,

I can not re-create this problem.

Are you sure it is coming from this plugin? Because you are not importing default value since it is in "{}" parentheses.

Can you provide more details on how you are using it?

**Comment by wty92911** [comment]
For example, "Import xxx from 'vue-audio-visual',the vscode tells me "Cannot find declaration file for module 'vue-audio-visual'." 
<img width="844" alt="image" src="https://user-images.githubusercontent.com/82802137/202347278-54cab7a4-2643-4d32-ad19-f00d2a85cbfc.png">
I installed vue-audio-visual by npm

**Comment by wty92911** [comment]
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/82802137/202352260-49df0fbe-33e1-4654-a304-e3e760fb5a01.png">

**Comment by wty92911** [comment]
OK,got it! It works after I add './dist/vue-audio-visual' in the package.json

**Comment by mikeda37** [comment]
@wty92911 
I got the same error.
Could you tell me how you fix the package.json more specifically?

@staskobzar 
Are there any other ways to fix this other than modifying files in your plugin?

**Comment by staskobzar** [comment]
@mikeda37 I can not re-create this problem so I do not know how to fix it.
if you provide details on how to re-create this bug or step-by-step instructions I can try when I have time
