### ISSUE TITLE
When AVWaveform's src uses ref variables, the waveform cannot be displayed normally

### ISSUE THREAD

**Issue by KunCheng-He** [staskobzar/vue-audio-visual#148]
## 1. src uses ref variables
```
<script setup lang="ts">
import { AVWaveform } from "vue-audio-visual"
const oriAudioUrl = ref<string>("")
const getAudioUrl = () => {
  const baseUrl = "http://127.0.0.1:8000/get-audio/?path="
  oriAudioUrl.value = baseUrl + "/upload_files/2024/01/20/test2_unzip/z1.mp3"
}
onBeforeMount(() => {
  getAudioUrl()
})
</script>

<template>
  <AVWaveform :src="oriAudioUrl" />
</template>
```
The result of running the above code is as shown below:

![image](https://github.com/staskobzar/vue-audio-visual/assets/48958733/feaa1da3-ee47-4eaf-b350-1a99bc54b17e)

## 2. src uses fixed string
```
<script setup lang="ts">
import { AVWaveform } from "vue-audio-visual"
...
</script>

<template>
  <AVWaveform src="http://127.0.0.1:8000/get-audio/?path=/upload_files/2024/01/20/test2_unzip/z1.mp3" />
</template>
```
The result of running the above code is as shown below:

![image](https://github.com/staskobzar/vue-audio-visual/assets/48958733/ee120d8b-aa14-40f6-911e-328ba0a7b5af)

## Please help me, thank you very much

+ My needs are as follows：
  + I hope that when using the ref variable, the waveform can be displayed normally.
  + When I pause playback and click a button to trigger a response event, I hope to get the current time of the player.

> I am still learning about vue and front-end. I hope someone can help me solve the above two problems. I have no ideas to solve the problem, and I have not found any available solutions. Thank you again！！！

**Comment by staskobzar** [comment]
Hello,
Unfortunatelly, this is not possible with waveform plugin. It downloads the audio data when mounted and then use it to build waveform graph.
What you can do is to remoount plugin with the new source when you need.
Another option is to use "v-if" vue directive. This directive remounts and rebuilds controlled html element. So you can try following scenario using v-if: hide element -> set new src -> show again

**Comment by KunCheng-He** [comment]
@staskobzar  Hello, Thank you so much
According to your suggestion, I made the following changes:
```
<script setup lang="ts">
import { AVWaveform } from "vue-audio-visual"
...
const flag = ref<boolean>(false)
const changeflag = () => {
  flag.value = !flag.value
}
</script>

<template>
  <AVWaveform v-if="flag" :src="oriAudioUrl" />
  <p v-else>false没有渲染</p>
  <el-button type="primary" @click.prevent="changeflag"
    >Click the button to perform a second rendering</el-button
  >
</template>
```
Make AVWaveform re-render through the flag variable, and everything will work fine

![image](https://github.com/staskobzar/vue-audio-visual/assets/48958733/4604463e-1108-4616-bc7b-782d47645019)

Thank you very much, but I have a second question. Now I want to add a new button. After clicking the button, I want to get the current playback progress of the player. What should I do?

**Comment by staskobzar** [comment]
For that you should use coposable approache to have better control on audio HTML element: "useAVWaveform"

Here is an example how it is done inside the waveform component:
https://github.com/staskobzar/vue-audio-visual/blob/master/src/components/AVWaveform.vue

It take couple more lines to build your waveform but you have full controll on your audio element

**Comment by KunCheng-He** [comment]
Thank you for your advice. I think I still need to try "useAVWaveform" and I don't quite understand how this component works.

**Comment by KunCheng-He** [comment]
Thank you very much, my problem has been solved by using "useAVWaveform". Thanks again.
