### ISSUE TITLE
Sample code doesn't seem to work

### ISSUE THREAD

**Issue by cfjedimaster** [staskobzar/vue-audio-visual#16]
I tried the sample code and noticed that only av-circle worked. I copied and pasted from the readme and only changed the MP3 location. You can see it online here: 

https://codesandbox.io/s/vueaudiovisual-test-pii5m

**Comment by cfjedimaster** [comment]
Sorry I should add, in the console, I see: 

![image](https://user-images.githubusercontent.com/393660/58734948-8cc11600-83be-11e9-819c-406db78272c4.png)

**Comment by staskobzar** [comment]
Hello,

Try to download your mp3 to the "public" folder and use it as:
```
<audio
            src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
            ref="foo"
            controls="true"
></audio>
```
To makes sure there are not CORS problems.
In my case it worked. May be that is your problem?

**Comment by staskobzar** [comment]
Source should be:
src="/SoundHelix-Song-1.mp3"

**Comment by cfjedimaster** [comment]
Ah - CORS issues then?

**Comment by staskobzar** [comment]
That would be my guess. Your code worked on my localhost when I downloaded mp3 to public.
I am using Chrome.

**Comment by cfjedimaster** [comment]
Ok, may I suggest that if a local mp3 is required that it be documented? (I don''t *think* it is, I could be wrong.)

**Comment by staskobzar** [comment]
Well, it is not strictly required. It just it must follow the rules. If mp3 is from different host then CORS attribute has to be set in <audio> element. Also remote host has to send some additional header following CORS specs.
There is also props for the element that can set CORS attribute (cors-anonym):
https://github.com/staskobzar/vue-audio-visual#common-props

**Comment by dingming1994** [comment]
Hi I am running into the same issue that only circle works with remote links. I have tried to put cors-anonym in many places but I cannot get it work. 

Any update on how the problem can be solved? thanks !

**Comment by dingming1994** [comment]
<table>
     <tr>
       <td rowspan="2">

       </td>
       <td>
         <audio v-bind:src="audioSrc" ref="foo" controls="true" crossorigin="anonymous"> </audio>
       </td>
       <td rowspan="2">
         <av-line ref-link="foo" :canv-height="40"   cors-anonym/>

       </td>
       <td>
         <av-circle ref-link="foo" :playtime="true"  cors-anonym/>

       </td>
       <td>
         <av-bars ref-link="foo"
           :bar-color="['#f00', '#ff0', '#0f0']"
           canv-fill-color="#000"
           :canv-width="26"
           :bar-space="1"
           :bar-width="12"
           :brick-height="6"
           cors-anonym
           />
       </td>
     </tr>

   </table>

**Comment by staskobzar** [comment]
@dingming1994 
I think it also depends on the source of the remote links. For example, they are supposed to send responses with header ```Access-Control-Allow-Origin: *```.

So the access to the link may be limited by the source.
There are not match control on the component side.
