### ISSUE TITLE
What does the calculation in each function_drawLine mean? 

### ISSUE THREAD

**Issue by 2474370906** [staskobzar/vue-audio-visual#17]

**Comment by 2474370906** [comment]
![image](https://user-images.githubusercontent.com/32259472/59401587-cd149100-8dcd-11e9-87df-176cbbabd2b4.png)

**Comment by staskobzar** [comment]
This is to calculate line height from the middle of the canvas (h / 2). The height has to fit the cancas height (v/255 * h/2).
![image](https://user-images.githubusercontent.com/147280/60037192-e693c380-967e-11e9-8075-2ef6f1a1f72c.png)

And to draw vertical line from the middle of the canvas up and every second line from the middle to bottom.
