### ISSUE TITLE
How to control the play / pause by code?

### ISSUE THREAD

**Issue by dingming1994** [staskobzar/vue-audio-visual#19]
Hi.

It is possible to control the play/pause status by JS code?

It seems that the play/pause for audio component will not be sync with the UI component.

**Comment by agravat202** [comment]
You may fire trigger .click() if you hide/remove default buttons.

**Comment by staskobzar** [comment]
Also, it is possible to use "ref-link" and create your own ```<audio>``` element. Then you can control your element with .play() and .pause() methods.

**Comment by dingming1994** [comment]
Hi Both. Thanks for the reply. Was away for another project previously. 

I have a weird cases when the av-line cannot vibrate. 

The following code works :

 ```
 <audio @canplay="getDuration" v-bind:src="audioSrc" ref="foo" v-bind:controls="false" id="name"  crossorigin="anonymous"> </audio>
 <av-line ref-link="foo" cors-anonym :canv-height="40" canv-class="canv-class" />

var aa = document.getElementById(‘ name’);
aa.play();

```

But the second segment is not working if I use ref instead of DOM

```
 <audio @canplay="getDuration" v-bind:src="audioSrc" ref="foo" v-bind:controls="false" id="name"  crossorigin="anonymous"> </audio>
 <av-line ref-link="foo" cors-anonym :canv-height="40" canv-class="canv-class" />

var aa = this.$refs.foo;
aa.play();

```

And I try to give each <audio> a unique id by :id and reference with getElementById, the av-line is not vibrate as well.

```
<audio @canplay="getDuration" v-bind:src="audioSrc" ref="foo" v-bind:controls="false" :id="nameId"  crossorigin="anonymous"> </audio>
 <av-line ref-link="foo" cors-anonym :canv-height="40" canv-class="canv-class" />

var aa = document.getElementById(this.nameId);
aa.play();
```


All the above three works with the audio, but just the <av-line> is not responding for case 2 & 3. I need to be able to control a list of <av-line> and <audio> by unique ID so ideally segment 3 is what I want to do. 

Seek your advice on how should I work it out.

Thanks so much.
