### ISSUE TITLE
The AudioContext was not allowed to start

### ISSUE THREAD

**Issue by lukas-pierce** [staskobzar/vue-audio-visual#22]
On page loading console warn:

```txt
The AudioContext was not allowed to start. 
It must be resumed (or created) after a user gesture on the page. 
https://goo.gl/7K7WLu
```

is it possible to do delayed initialization?

**Comment by qbunt** [comment]
I am also experiencing this, the above link points to a changed policy in audio auto-start rules, and would directly impact this plugin without some sort of delayed execution in the manner of a click or similar.

**Comment by staskobzar** [comment]
Hello,
I will try to fix it this weekends. If you have a patch, please, feel free to provide pull request.

**Comment by qbunt** [comment]
Unfortunately, not sure there is an easy fix here, you'd have to wait for some kind of user interaction first and then create an audio context and/or resume it, it's definitely not conducive to using inside a component like this without attaching some click event first.
