### ISSUE TITLE
AudioContext is undefined on beforeDestroy hook

### ISSUE THREAD

**Issue by okolomiets** [staskobzar/vue-audio-visual#23]
The issue is easily reproducible when the parent component is destroyed.

> TypeError: Cannot read property 'close' of undefined
>     at VueComponent.beforeDestroy (AvBase.js?7883:192)

Do we need a simple check for the AudioContext to avoid errors?

**Comment by staskobzar** [comment]
Thanks. Fixed. Will be available in 1.4.0
