### ISSUE TITLE
How can I redraw AvWaveform graphics when audio url changes

### ISSUE THREAD

**Issue by hello-lun** [staskobzar/vue-audio-visual#26]
How can I redraw AvWaveform graphics when audio url changes？
i use ref-link to link audio，but when audio url change, AvWaveform not change.
![image](https://user-images.githubusercontent.com/34638158/72214915-9ad73780-3546-11ea-9ed4-558adcb581c7.png)

**Comment by staskobzar** [comment]
AvWaveform upload the audio file in the background to get all data for drawing waveform.
Try to re-create the hole element with new url.

**Comment by hello-lun** [comment]
resolve
