### ISSUE TITLE
Why the page freezes after drawing <av-waveform>

### ISSUE THREAD

**Issue by hello-lun** [staskobzar/vue-audio-visual#27]
Draw 6 av-waveform at the same time on one page, redraw 6  av-waveform on the next page, and the page will freeze after ten minutes. The cpu started to rise. How to solve it？
![image](https://user-images.githubusercontent.com/34638158/72915305-05744880-3d7b-11ea-83c0-ff90f99888f3.png)Feeling is this function still in operation after component destroyed, which lead to this. <this.waveform> is not recycling by GC, the passage of time will be a memory leak, Cause the page to freeze

**Comment by staskobzar** [comment]
Should be ok in ver 2.0.0
Please, try.

**Comment by hello-lun** [comment]
> Should be ok in ver 2.0.0
> Please, try.

thinks
