### ISSUE TITLE
[Bug] MediaElementAudioSource outputs zeros due to CORS access restrictions

### ISSUE THREAD

**Issue by SohrabZ** [staskobzar/vue-audio-visual#3]
I received this error:

`MediaElementAudioSource outputs zeros due to CORS access restrictions`

Here is a fix according to https://stackoverflow.com/questions/31308679/mediaelementaudiosource-outputs-zeros-due-to-cors-access-restrictions-local-mp3

in AvBase.js:

```js
createHTMLElements: function () {
    ...
    audio.crossOrigin = 'anonymous'
    ...
  },
```

**Comment by staskobzar** [comment]
Fixed. Will be available in next release.
Thank you, Sohrab.

**Comment by wty92911** [comment]
The core parameter was deleted in the new release,So how can I deal with it ?

**Comment by dinalUdagedara** [comment]
> The core parameter was deleted in the new release,So how can I deal with it ?

@wty92911  any updates ?
