### ISSUE TITLE
I cannot use ref-link to link audio

### ISSUE THREAD

**Issue by hongquangraem** [staskobzar/vue-audio-visual#34]

**Comment by staskobzar** [comment]
Hello,
Sorry, I can not accept this kind of error report. Please, describe your problem and welcoming and inclusive language also would be appeciated.

Thank you

**Comment by hongquangraem** [comment]
Sorry for my bad error report!
I try to use audio tag with ref, and <av-waveform /> with ref-link to link these tag but it doesn't work.
It always throw exception: "Not found src"
So I have to use alone <av-waveform /> by itselft with prop audio-src

**Comment by staskobzar** [comment]
Can you provide the code with the problem?
