### ISSUE TITLE
the audio restarts when i click on the wave in the av-waveform component

### ISSUE THREAD

**Issue by Mpiranha** [staskobzar/vue-audio-visual#35]
The audio restarts when I click on the waveform in the av-waveform, this is my code below.
Please I need help

  <av-waveform 
        audio-src="/audio/file_example_MP3_700KB.mp3"
        :playtime-clickable="true"
        ></av-waveform>

**Comment by Mpiranha** [comment]
<av-waveform 
        audio-src="/audio/file_example_MP3_700KB.mp3"
        :playtime-clickable="true"
        ></av-waveform>

**Comment by staskobzar** [comment]
Yes, happened to me in development mode. Try in production, should work.
Also, try to run your dev server with --https option.
Check demo: https://staskobzar.github.io/vue-audio-visual/

**Comment by Mpiranha** [comment]
Okay, thanks. I'll try it out and I'll get back to you

**Comment by Mpiranha** [comment]
running the dev server with --https fixed it Thanks. 
Is it possible to add a custom control? if Yes, How?

**Comment by staskobzar** [comment]
Glad it helped.
Do you mean custom control for audio play? like pause, forward etc?
If yes, this is not implemented.

**Comment by Mpiranha** [comment]
Alright, thanks.
