### ISSUE TITLE
av-circle playtime in in the center - UI 

### ISSUE THREAD

**Issue by eliyahuKriel** [staskobzar/vue-audio-visual#42]
HI thanks for this great plugin!
i use the `av-circle` component - but the playtime is not in the middle, here is my code :

`     <av-circle
                :outline-width="0"
                :progress-width="5"
                :outline-meter-space="5"
                :playtime="true"
                playtime-font="18px Monaco"
                :audio-src="file()"
        ></av-circle>
`

![image](https://user-images.githubusercontent.com/59528365/87281024-78c17080-c4fb-11ea-9f30-ef18dc5a0fb8.png)

**Comment by staskobzar** [comment]
Hello,
Thanks!
I tried to reproduce with the code you gave and it looks OK. However, on your screenshot the element is shifted to right and I guess that you have some additional CSS or javascript which does it. Also, you might change the width of the canvas element.
Make sure your canvas width and height are the same.
Also, in your case it may help using ```ref-link``` property to decouple audio and canvas elements. After that wrap the element in "div" and change position or width of the "div" but not of the canvas element.
