### ISSUE TITLE
Its possible to pass a custom axios instance?

### ISSUE THREAD

**Issue by Dagdelo** [staskobzar/vue-audio-visual#53]
I'm having some trouble using this awesome component because my project uses an Axios instance with several configs... Idk, perhaps a prop? Passing the instance to be used. I'm talking specifically of [this](https://github.com/staskobzar/vue-audio-visual/blob/master/src/components/AvWaveform.js#L176).

**Comment by staskobzar** [comment]
Hello Henrique,
I knew that this will be required sooner or later and I appreciate you've contributed your nice solution for that.
The pull request is still marked as work in progress:
![image](https://user-images.githubusercontent.com/147280/92238999-4a6f6a00-ee88-11ea-8bc5-9383c3baca7a.png)
Let me know if you are still planning to do some work or is it ready to merge? I will create a new release as long as it is ready.
Thanks!

**Comment by staskobzar** [comment]
included in new release v2.2.0
Thank you for the contribution.
Have a good day!
