### ISSUE TITLE
Wave Form is not generating for mono channel mp3

### ISSUE THREAD

**Issue by rohitbahekar** [staskobzar/vue-audio-visual#57]
I am trying to generate waveform of mp3 file mentioned  below

http://www.mediafire.com/file/m0kx030imexx5fi/5f7b1c36cff2a806d352910f.mp3.mp3/file

Audio channels: mono
sampling 44.1 KHz

please guide me what needs to be done

**Comment by staskobzar** [comment]
Hello,
Please, check the documentation in README.md file. You also can check an example in "demo" folder:
https://github.com/staskobzar/vue-audio-visual/blob/master/demo/src/components/AvWaveform.vue

**Comment by rohitbahekar** [comment]
I have tried demo and its working fine but waveforms are not getting
generated for the file provided by me

**Comment by staskobzar** [comment]
everything works for me. I have downloaded the file and put in public directory
![image](https://user-images.githubusercontent.com/147280/95090353-2acf9980-06f3-11eb-957c-e8b5b3ee21c6.png)
```vue
<template>
  <div>
    <h4><code>av-waveform</code> component</h4>
    <a target="blank" href="https://github.com/staskobzar/vue-audio-visual/blob/master/demo/src/components/AvWaveform.vue">
    Example source code</a>
    <av-waveform
      audio-src="5f7b1c36cff2a806d352910f.mp3.mp3"
    ></av-waveform>
  </div>
</template>

<script>
export default {
  name: 'av-waveform-demo'
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
```

**Comment by rohitbahekar** [comment]
It was a CORS issue from AWS S3.

thanks for clarification
