### ISSUE TITLE
currentTime is always set as 0

### ISSUE THREAD

**Issue by finn-dev** [staskobzar/vue-audio-visual#59]
Hi.
First of all, thanks for your plugin.
This is really useful one.

----------------
I am now facing problems on seek from <av-waveform>
I checked and in AvWaveform.js -- line 395
`this.audio.currentTime = e.offsetX / this.canvWidth * this.duration`

While i am debugging, i found out that, right side is correct, but when trying to update currentTime, it is becoming 0.
So player plays from the beginning again.

Any idea?
With your demo, it is working fine, but on my hand it s not. :(
Hope for your quick support. :)

Thank you.

**Comment by staskobzar** [comment]
Hi,

I actually had this problem too and I noticed that it appears during development but works fine in production.
Then it also happened to work fine in development too. After that I was not be able to reproduce it, probably I have changed something that fixed it.

Can you post a code that reproduce this problem, please?
I will try to take a look and fix this week-end.
Thanks

**Comment by finn-dev** [comment]
Hi.
Thanks for your kind, quick response.
I think i found the problem.
Code is very simple, just same as demo.
Looks like, the problem is my platform.
Even when i put simple <audio> tag, it was also not working for seek.
Let me check my platform again, and once figure out, then will report back to you again.

Thank you.

PS: Mine is Laravel-mix + Vue

**Comment by staskobzar** [comment]
Interesting...
I think I had this problem with rails + webpacker + vue.
My last project was vue-cli based and I do not remember I had this problem.

Thanks for the details

**Comment by finn-dev** [comment]
Hi

Back.
So after npm uninstall vue-audio-visual, it is again working with simple <audio> tag
So looks like issue on your side :)
Kindly check again and report back to me.

Thank you.

**Comment by finn-dev** [comment]
same.
just removed node_modules and try again, but still stuck.

**Comment by staskobzar** [comment]
Sorry, I never tried it on windows but I can build it on my PC and github can build it on its platform.
make sure you have the latest node version. Maybe there is environment problems.

**Comment by finn-dev** [comment]
Hi
I just upgrade to v14.15.0
And still same.
Is this one working on your side?

**Comment by staskobzar** [comment]
I have node v14.12.0. I also have another server with v10.18.1, just tried and it also works.
Just installed the latest node  v14.15.0 on another machine and it also works.
Those are all linux machines.

**Comment by finn-dev** [comment]
I tried on Windows, let me try in linux.

**Comment by finn-dev** [comment]
![image](https://user-images.githubusercontent.com/67330526/97752669-c1c22280-1af4-11eb-8e4c-eb15aa3c0be3.png)
Now getting this one.

**Comment by finn-dev** [comment]
Finally running in Linux.
I will check my platform.

**Comment by staskobzar** [comment]
Yeah, the error I got too. just a minor syntax error. I will push the fix later to github.

**Comment by finn-dev** [comment]
Thank you. Hope you fix very soon.
