### ISSUE TITLE
playtime prop is not used

### ISSUE THREAD

**Issue by andreasvirkus** [staskobzar/vue-audio-visual#60]
Hi, thanks for a great audio visualization library! `<3`

I believe the `drawTime` function for Waveform should be called conditionally, only when `props.playtime` is true

https://github.com/staskobzar/vue-audio-visual/blob/0d6f2dde6fe39c0e3da696f0529895b574b7c326/src/components/AvWaveform.js#L293

Would you accept a PR for this change?

**Comment by staskobzar** [comment]
Hello Andreas,

Yes, sure. Please, create PR. 
Thank you!
