### ISSUE TITLE
How could I export frame by frame?

### ISSUE THREAD

**Issue by tudorradubarbu** [staskobzar/vue-audio-visual#64]
Hello and first of all, awesome implementation.

I want to export this to FFmpeg, but, is it possible to export frame by frame animation?
Do you have any code advice on this one?

**Comment by staskobzar** [comment]
Hello,

I am not sure I got the question, sorry. You want to export to use with utility ffmpeg?
The animation is based on HTTP element "canvas" and I do not know if there any way to export this to something else. Maybe it exists but I do not know.

If you want to build a waveform graph locally you can check projects like this: https://github.com/bbc/audiowaveform
