### ISSUE TITLE
No visualizations when built as a part of web component using Vue CLI 4

### ISSUE THREAD

**Issue by rovshan-b** [staskobzar/vue-audio-visual#71]
I am using av-waveform component to display visualizations when recording from microphone.
This is screenshot of my Vue app when built as part of normal web page:

![image](https://user-images.githubusercontent.com/12267949/114640132-81401500-9ce0-11eb-8b75-71bda8caf958.png)

and when built the same in web component mode it does not appear (voice gets recorded normally. i.e. no problems with retrieving and setting user media. no changes in code between normal build and web component mode build):

![image](https://user-images.githubusercontent.com/12267949/114640384-1216f080-9ce1-11eb-8d52-31d0e811f03e.png)

there are no errors in browser console or network tab.

build command: `yarn build --target wc --inline-vue --name=my-component`

**Comment by staskobzar** [comment]
Please, try new version 2.3.0 which is compatible with vue3
