### ISSUE TITLE
Uncaught (in promise) TypeError: h is not a function

### ISSUE THREAD

**Issue by dugudongfangshuo** [staskobzar/vue-audio-visual#77]
Uncaught (in promise) TypeError: h is not a function

**Comment by nsssayom** [comment]
in `node_modules/vue-audio-visual/src/components/AvMedia.js` replace `render: h => h('div')` with 

```
render () {
        return h('div')
    }
```
And add `import { h } from "vue";` 

Not the recommended way to update node modules though. But works for the time being..

**Comment by staskobzar** [comment]
New version 2.3.0 which is compatible with vue3 (as mentioned in your pull request)
Please, close this issue if it works fine
