### ISSUE TITLE
how to audio-src play on method

### ISSUE THREAD

**Issue by sankamaduranga** [staskobzar/vue-audio-visual#78]
:audio-src="'http://127.0.0.1:8000/tracks/'+item.mp3_link" how to method play audio

**Comment by staskobzar** [comment]
Sorry, I do not understand the question

**Comment by sankamaduranga** [comment]
> Sorry, I do not understand the quesi side v-for funtion not working using ref and ref-link

**Comment by sankamaduranga** [comment]
> Sorry, I do not understand the question

not working inside v-for loop via ref/ref-link

**Comment by staskobzar** [comment]
check console for javascript errors and network
also make sure ```item.mp3_link``` has correct link and not the whole url link but only a path part

**Comment by alectrocute** [comment]
@sankamaduranga Post full example code, an actual reproducible example.
