### ISSUE TITLE
problem in waveform

### ISSUE THREAD

**Issue by nemesisKO** [staskobzar/vue-audio-visual#85]
DOMException: Unable to decode audio data
my snippet:

import AvWaveform from 'vue-audio-visual/src/components/AvWaveform'
`<audio ref="foo"></audio>`
`<av-waveform ref-link="foo" :audio-src="..." ></av-waveform>`

by the way avBars works fine with this snippet

**Comment by nemesisKO** [comment]
> DOMException: Unable to decode audio data my snippet:
> 
> import AvWaveform from 'vue-audio-visual/src/components/AvWaveform' `<audio ref="foo"></audio>` `<av-waveform ref-link="foo" :audio-src="..." ></av-waveform>`
> 
> by the way avBars works fine with this snippet

when i remove ref-link from component tag it works but i want to hide the html player

**Comment by staskobzar** [comment]
Hello,
You need to put src to your "audio" element if you want to use external audio element. Do not use audio-src:
```vue
<audio ref="foo" src="file_example_MP3_1MG.mp3" controls></audio>
<av-waveform ref-link="foo"></av-waveform>
```
