### ISSUE TITLE
Is it possible it's not up-to-date when doing npm install?

### ISSUE THREAD

**Issue by anthomaxcool** [staskobzar/vue-audio-visual#9]
I see the commit for the cors-anonym fix, but I can't see in the code from my project after doing "npm install --save vue-audio-visual".

Thanks

**Comment by staskobzar** [comment]
This commit is not in release yet. You can clone the whole project and install from local folder, something like: npm install /path/to/vue-audio-visual 
or npm install git+https://github.com/staskobzar/vue-audio-visual.git
